#! /usr/bin/env python
from cli_tools import CLI_Instance

from sys import argv

cli = CLI_Instance()

command = argv[1]

if command == 'doc':
    print(cli.doc(argv[2]))
elif command == 'default':
    print(cli.default(argv[2]))
elif command == 'version':
    print(cli.version())
elif command == 'summary':
    print(cli.summary(argv[2]))
elif command == 'search':
    print(cli.search_name(*argv[2:]))
elif command == 'searchd':
    print(cli.search_doc(*argv[2:]))
