#! /usr/bin/env python
from cli_tools import CLI_Instance

from sys import argv

cli = CLI_Instance()

if argv[1] == 'doc':
    print(cli.doc(argv[2]))
elif argv[1] == 'default':
    print(cli.default(argv[2]))
